name: cd.yml

on:
  push:
    branches: [ main ]  # Change to your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (adjust if needed)
        run: sudo apt update && sudo apt install openssh-client -y  # Needed for PAT-based SSH

      - name: Configure SSH using PAT
        uses: shivfu/ssh-add@v1
        with:
          private_key: ${{ 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 }}  # Replace with your PAT secret name
          host_key_checking: no  # **WARNING:** Consider security implications before disabling host key checking

      - name: Connect to Ubuntu server
        run: ssh bteg@172.30.10.249  # Replace with your server details

      - name: Update dependencies (adjust if needed)
        run: ssh bteg@172.30.10.249 'sudo apt update && sudo apt upgrade -y'  # Update on server

      - name: Install dependencies (if needed on server)
        run: ssh bteg@172.30.10.249 'npm install || yarn install'  # Run npm install or yarn install based on your setup

      - name: Build Next.js application (optional, can be built locally)
        run: ssh ubuntu@your_server_address 'npm run build || yarn build'  # Run build command on server (optional)

      - name: Start or restart your application (adjust based on your setup)
        run: ssh bteg@172.30.10.249 'nohup /home/bteg/nextjs/nextjs-blog &'  # Replace with your start command if needed

