name: Next.js CI/CD

on:
  push:
    branches: [ main ]  # Adjust for your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Adjust for your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build  # Adjust if you use a different build command

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}  # Consider using SSH keys for better security
          port: 22  # Typical SSH port (adjust if needed)
          remotePath: /home/bteg/nextjs/nextjs-blog  # Adjust for your server directory
          localPath: ./out  # Adjust if you have a different output directory
        # Exclude unnecessary files
